--------------------------------------------------------
--  File created - Tuesday-December-19-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REIMBURSEMENT
--------------------------------------------------------

  CREATE TABLE "ERS"."REIMBURSEMENT" 
   (	"REIMBUSMENTID" NUMBER(*,0), 
	"AMOUNT" NUMBER, 
	"DATESUBMITTED" DATE, 
	"DATERESOLVED" DATE, 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"AUTHORID" NUMBER(*,0), 
	"RESOLVERID" NUMBER(*,0), 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ERS.REIMBURSEMENT
SET DEFINE OFF;
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (4,9.95,to_date('05-DEC-17','DD-MON-RR'),to_date('11-DEC-17','DD-MON-RR'),'Enthuware Software',3,2,'approved');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (5,9.95,to_date('06-DEC-17','DD-MON-RR'),to_date('11-DEC-17','DD-MON-RR'),'Enthuware Software',4,2,'approved');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (6,99.99,to_date('07-DEC-17','DD-MON-RR'),to_date('15-DEC-17','DD-MON-RR'),'Code Fuel --Coffee',4,2,'denied');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (7,19.99,to_date('11-DEC-17','DD-MON-RR'),null,'OCA Study Guide',3,2,'open');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (8,1337.347,to_date('19-DEC-17','DD-MON-RR'),null,'OCA Study Guide',3,2,'open');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (9,999,to_date('19-DEC-17','DD-MON-RR'),null,'dressing to the nines',1,2,'open');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (1,9.95,to_date('04-DEC-17','DD-MON-RR'),to_date('11-DEC-17','DD-MON-RR'),'Enthuware Software',1,2,'approved');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (2,15.99,to_date('12-DEC-17','DD-MON-RR'),null,'Another Expense',1,2,'open');
Insert into ERS.REIMBURSEMENT (REIMBUSMENTID,AMOUNT,DATESUBMITTED,DATERESOLVED,DESCRIPTION,AUTHORID,RESOLVERID,STATUS) values (3,15.99,to_date('04-DEC-17','DD-MON-RR'),to_date('11-DEC-17','DD-MON-RR'),'Pizza party',1,2,'denied');
--------------------------------------------------------
--  DDL for Index PK_REIMBUSMENTID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERS"."PK_REIMBUSMENTID" ON "ERS"."REIMBURSEMENT" ("REIMBUSMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_REIMID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ERS"."TRG_REIMID" 
  BEFORE INSERT ON REIMBURSEMENT
  FOR EACH ROW
BEGIN
  :new.REIMBUSMENTID := reim_id_seq.nextval;
END;

/
ALTER TRIGGER "ERS"."TRG_REIMID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_REIM_DATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ERS"."TRG_REIM_DATE" BEFORE INSERT ON REIMBURSEMENT
FOR EACH ROW
BEGIN
    :NEW.DATESUBMITTED := SYSDATE;
END;

/
ALTER TRIGGER "ERS"."TRG_REIM_DATE" ENABLE;
--------------------------------------------------------
--  Constraints for Table REIMBURSEMENT
--------------------------------------------------------

  ALTER TABLE "ERS"."REIMBURSEMENT" ADD CONSTRAINT "PK_REIMBUSMENTID" PRIMARY KEY ("REIMBUSMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ERS"."REIMBURSEMENT" MODIFY ("AUTHORID" NOT NULL ENABLE);
  ALTER TABLE "ERS"."REIMBURSEMENT" MODIFY ("REIMBUSMENTID" NOT NULL ENABLE);
